# config.py
# =============================================================================
# LEGACY research-scenario settings for the VSA / OPM distributed hydrologic
# model.  Values only — no logic.  Changing OUTPUT_DIR (§1) cascades to every
# path derived from it.
#
# The model itself now lives in the pip-installable `vsa_opm` package and is
# configured with vsa_opm.config.OpmConfig (YAML/JSON via the `vsa-opm` CLI).
# This module is kept as the scenario file for the repository's research
# workflows (tools/runner.py, tests/): they import it and pass it directly as
# the cfg object — every core function accepts any object with these
# attributes.  It also loads via `vsa-opm run -c config.py`.
#
# Contents
#   1.  Event & scenario          ← DEM, output folder, event timing, GEE
#   2.  Watershed pre-processing outputs (process_dem.py)
#   3.  Precipitation
#   4.  Runoff generation
#   5.  OPM / VSA parameters
#   6.  SERVES / GEE soil-moisture deficit (SD_max & phi)
#   7.  Manning's roughness
#   8.  Grid & numerical limits
#   9.  Outputs
#   10. Compute backend
# =============================================================================


# ═════════════════════════════════════════════════════════════════════════════
# 1.  EVENT & SCENARIO
# ═════════════════════════════════════════════════════════════════════════════
# Change these five knobs to define a new event/scenario.  Everything else
# (IMERG window, SERVES date, derived paths) flows from them automatically.

# Path to the Digital Elevation Model (DEM) file
DEM_PATH = "./dem_100m.tif"

# Target Coordinate Reference System (CRS) for reprojection.
TARGET_CRS_EPSG = "EPSG:32645"

# Output point for watershed delineation (latitude, longitude)
OUTPUT_POINT = (27.632222, 85.293333)  # (lat, lon)

# Output directory for all generated files.  This is the ONE knob that defines a
# scenario — every derived path below (rasters, IMERG data, deficit raster,
# hydrograph) hangs off it, so changing it here moves the whole scenario.
OUTPUT_DIR = "outputs collection/multiple_imerg/"

# EVENT_START_UTC: event / simulation start in UTC ("YYYY-MM-DD HH:MM").
#   Single source of truth for the event date, used by:
#     • SERVES antecedent query  — date portion is the antecedent moisture date
#     • IMERG download window    — start = EVENT_START_UTC + IMERG_UTC_OFFSET_HOURS
#                                  end   = start + TOTAL_SIMULATION_TIME_HOURS
#   None → fallback to IMERG_START_LOCAL / IMERG_END_LOCAL if set (backward compat).
EVENT_START_UTC = None

# Total simulation length in hours.
#   Also defines the IMERG download window end when EVENT_START_UTC is set.
TOTAL_SIMULATION_TIME_HOURS = 96

# UTC offset for display and IMERG local-time conversion.
#   Nepal Standard Time (NPT) = UTC + 5:45 → 5.75
#   Set to 0.0 if you work in UTC throughout.
IMERG_UTC_OFFSET_HOURS = 5.75

# Lookup CSVs: land-cover class → root zone depth, Manning's n.
LULC_LOOKUP_CSV = 'lulc_lookup.csv'   # ESA WorldCover (used when MANNINGS_N_SOURCE='lulc')
LCZ_LOOKUP_CSV  = 'lcz_lookup.csv'    # WUDAPT LCZ     (used when MANNINGS_N_SOURCE='lcz')

# Google Earth Engine cloud project ID (required for IMERG, SERVES, LULC/LCZ download).
# Also settable via the GEE_PROJECT environment variable.
GEE_PROJECT = 'ee-sauravbhattarai1999'


# ═════════════════════════════════════════════════════════════════════════════
# 2.  WATERSHED PRE-PROCESSING OUTPUTS  (written by process_dem.py)
# ═════════════════════════════════════════════════════════════════════════════
# Derived from OUTPUT_DIR so changing the scenario folder in §1 cascades here.

ROUTING_DEM_PATH            = OUTPUT_DIR + "clipped_dem.tif"
ROUTING_FLOW_DIR_PATH       = OUTPUT_DIR + "flow_direction.tif"
ROUTING_FLOW_ACCUM_PATH     = OUTPUT_DIR + "clipped_flow_accumulation.tif"
ROUTING_WATERSHED_MASK_PATH = OUTPUT_DIR + "watershed.tif"

# Watershed boundary vector (auto-generated by process_dem.py).
OPM_WATERSHED_GEOJSON = OUTPUT_DIR + 'watershed.geojson'


# ═════════════════════════════════════════════════════════════════════════════
# 3.  PRECIPITATION
# ═════════════════════════════════════════════════════════════════════════════

# --- Uniform event (used when PRECIP_METHOD = 'uniform') ---
RAIN_INTENSITY_MM_HR = 20.0         # mm / hour
RAIN_DURATION_HOURS  = 3.0          # hours (rainfall stops; remainder is recession)

# --- Method selection ---
# 'uniform'        → RAIN_INTENSITY_MM_HR / RAIN_DURATION_HOURS above
# 'thiessen'       → Voronoi nearest-gauge spatial weighting (CSV gauges)
# 'idw'            → Inverse Distance Weighting (PRECIP_IDW_POWER)
# 'imerg_thiessen' → NASA GPM IMERG V07 from GEE, Thiessen weighting
# 'imerg_idw'      → same IMERG source, IDW weighting
PRECIP_METHOD          = 'thiessen'
PRECIP_GAUGE_FILE      = "test_data/opm_format/202407_202408/gauges.csv"
PRECIP_TIMESERIES_FILE = "test_data/opm_format/202407_202408/timeseries.csv"
PRECIP_IDW_POWER       = 2.0

# PRECIP_EXCLUDE_OUTSIDE_STATIONS: drop gauge centroids that fall outside the watershed.
#   False (default) → keep all; boundary cells get the nearest outside station.
#   True  → outside stations excluded; boundary cells fall to nearest inside station.
PRECIP_EXCLUDE_OUTSIDE_STATIONS = False

# --- IMERG source (used when PRECIP_METHOD = 'imerg_thiessen' / 'imerg_idw') ---
# Download strategy: one GEE getRegion call per event, each 0.1° pixel → pseudo-gauge.
#
# Event window is AUTO-DERIVED from §1:
#   IMERG_START_LOCAL = EVENT_START_UTC  + IMERG_UTC_OFFSET_HOURS   (local civil time)
#   IMERG_END_LOCAL   = EVENT_START_UTC  + TOTAL_SIMULATION_TIME_HOURS + IMERG_UTC_OFFSET_HOURS
#
# Override: set IMERG_START_LOCAL / IMERG_END_LOCAL explicitly to bypass derivation.
IMERG_START_LOCAL   = None   # "YYYY-MM-DD HH:MM" local  |  None → auto from §1
IMERG_END_LOCAL     = None   # "YYYY-MM-DD HH:MM" local  |  None → auto from §1

PRECIP_IMERG_DIR          = OUTPUT_DIR + "imerg/"
IMERG_DATASET             = "NASA/GPM_L3/IMERG_V07"
IMERG_BAND                = "precipitation"          # mm/hr (V07 calibrated)
PRECIP_IMERG_FORCE_DOWNLOAD = False
IMERG_BBOX_BUFFER_M       = 11132  # ~1 IMERG pixel; keeps edge cells covered


# ═════════════════════════════════════════════════════════════════════════════
# 4.  RUNOFF GENERATION
# ═════════════════════════════════════════════════════════════════════════════
# Controls whether a runoff-generation model transforms rainfall into effective
# runoff before it enters the kinematic-wave router.
#   'none'        → all rainfall is direct runoff (default, backward compatible)
#   'coefficient' → multiply by static spatial Cf raster (0–1)
#   'raster'      → pre-computed runoff raster time series
#   'scs_cn'      → SCS Curve Number: per-cell CN raster + cumulative rainfall
#   'vsa_opm'     → Variable Source Area: Pradhan & Ogden (2010) OPM
RUNOFF_SOURCE           = 'vsa_opm'
RUNOFF_COEFFICIENT_PATH = "runoff/runoff_coefficient.tif"
RUNOFF_RASTER_MANIFEST  = "runoff/manifest.csv"
RUNOFF_CN_PATH          = "runoff/curve_number.tif"
RUNOFF_SCS_Ia_FACTOR    = 0.2       # SCS initial abstraction ratio (standard 0.2)


# ═════════════════════════════════════════════════════════════════════════════
# 5.  OPM / VSA PARAMETERS  (used when RUNOFF_SOURCE = 'vsa_opm')
# ═════════════════════════════════════════════════════════════════════════════

# RUNOFF_MECHANISMS: which of the three runoff-generation mechanisms are active
#   (used when RUNOFF_SOURCE='vsa_opm').  Include any subset — they are fully
#   orthogonal, so this is the ONE place to compose the runoff model:
#     'vsa'        → saturation-excess / Dunne (the OPM Variable Source Area)
#     'horton'     → infiltration-excess via Green-Ampt (needs the OPM_GA_* params)
#     'impervious' → urban shedding (needs IMPERVIOUS_SOURCE ≠ 'none')
#   Effective runoff per cell:
#     rain · [ Imp + (1 − Imp) · max(in_VSA, infil_excess_frac) ]
#   with the in_VSA / excess / Imp terms switched on only when their mechanism is
#   listed.  Examples: ['vsa','impervious'] → no Horton; ['impervious'] → urban
#   only; [] → no hillslope runoff (router still moves any seeded/baseflow water).
#   None / unset → legacy behaviour: VSA always on, Horton from OPM_INFILTRATION,
#   impervious from IMPERVIOUS_SOURCE (fully backward compatible).
RUNOFF_MECHANISMS = ['vsa', 'horton', 'impervious']

# OPM_SD_MAX_INITIAL: root zone depth D — vertical height of the soil column
#   at the catchment divide [m].  When OPM_SD_SOURCE='gee', overridden by SERVES.
OPM_SD_MAX_INITIAL = 0.1    # m  (physical height, not water volume)

# OPM_SD_MIN: minimum saturation deficit [m] — floor on SD_max(t) as the sandbox
#   wets up (Rf = SD_min/SD_max drives Eq 4's A_t).  Only meaningful when 'vsa'
#   is in RUNOFF_MECHANISMS (the sandbox is skipped entirely otherwise).
OPM_SD_MIN         = 0.001  # m

# OPM_Q_MAX: observed baseflow / initial discharge at the outlet [m³/s].
#   Used in Eq 10 (Pradhan & Ogden 2010) to calibrate the initial A_t.
OPM_Q_MAX          = 100    # m³/s  — set to observed pre-storm discharge

# OPM_PHI: drainable porosity [-].  When OPM_SD_SOURCE='gee', overridden by SoilGrids.
OPM_PHI            = 0.35

# OPM_K_SAT: field-scale lateral saturated hydraulic conductivity [m/day].
OPM_K_SAT          = 44.0   # m/day  (calibrated)

# OPM_PER_POLYGON: each gauge zone gets its own OPM sandbox (z, SD_max, A_t).
OPM_PER_POLYGON    = True

# ── Infiltration model (Green-Ampt) ──────────────────────────────────────────
# Adds an infiltration limit on top of the VSA saturation-excess mechanism.
# AUTHORITATIVE AND INDEPENDENT of RUNOFF_MECHANISMS (this is the one place
# that decides it, regardless of whether 'horton' is also selected there):
#   'none'       → the sandbox recharges from uncapped rainfall: ALL rain
#                  reaches the divide's water table every step.
#   'green_ampt' → per-cell Green-Ampt infiltration capacity f_p = K·(1 + ψ·Δθ₀/F)
#                  caps how much of the divide cell's rain can recharge the
#                  sandbox (z → SD_max(t) → A_t), whether or not 'horton' is in
#                  RUNOFF_MECHANISMS.  Separately, when 'horton' IS also in
#                  RUNOFF_MECHANISMS, the same f_p also generates infiltration-
#                  excess (Hortonian) runoff that's added to the output at
#                  every non-VSA cell.  Δθ₀ is derived from the SERVES deficit
#                  raster ÷ root-zone depth (no extra download).
# In short: OPM_INFILTRATION = "is the sandbox physically realistic".
#           RUNOFF_MECHANISMS = "which mechanisms' runoff counts in the output".
OPM_INFILTRATION = 'green_ampt'   # 'green_ampt' | 'none'

# Wetting-front suction head ψ [m] for Green-Ampt.
# OPM_GA_SUCTION_SOURCE:
#   'scalar'  → uniform OPM_GA_SUCTION_M below (typical loam ≈ 0.1–0.2 m).
#   'texture' → per-cell ψ from SoilGrids sand/clay → USDA texture class →
#               Rawls (1983) Green-Ampt suction table.  ψ enters GA only as the
#               product ψ·Δθ₀, so this makes ψ spatial like Δθ₀.  Cells with no
#               texture data fall back to OPM_GA_SUCTION_M.
OPM_GA_SUCTION_SOURCE = 'texture'
OPM_GA_SUCTION_M      = 0.15   # uniform value / nodata fallback [m]

# Vertical surface infiltration capacity K_v [mm/hr] for Green-Ampt.
#   IMPORTANT: this is the *vertical* (surface) saturated conductivity, NOT the
#   lateral transmissivity OPM_K_SAT (44 m/day) that drives the sandbox Darcy
#   drainage.  Vertical Ksat is far smaller (sand ≈ 50, loam ≈ 10, clay ≈ 1 mm/hr);
#   using the lateral value here would make f_p ≫ rain and Green-Ampt would never
#   generate infiltration-excess runoff.
#
# OPM_GA_KSAT_SOURCE:
#   'scalar' → uniform OPM_GA_KSAT_MMHR below.
#   'gee'    → per-cell HiHydroSoil v2.0 Ksat (vertical saturated conductivity),
#              downloaded aligned to the routing DEM and cached to
#              OPM_GA_KSAT_RASTER.  Cells with no data fall back to OPM_GA_KSAT_MMHR.
#   'raster' → pre-computed mm/hr GeoTIFF at OPM_GA_KSAT_RASTER.
OPM_GA_KSAT_SOURCE = 'gee'
OPM_GA_KSAT_MMHR   = 12.0    # uniform value / nodata fallback [mm/hr]
OPM_GA_KSAT_RASTER = None    # None → auto-path: {OUTPUT_DIR}/ksat_hihydro.tif
# Calibration multiplier applied to the gridded Ksat (HiHydroSoil Ksat is
# uncertain; one knob to scale infiltration capacity up/down).
OPM_GA_KSAT_SCALE  = 1.0

# ── Impervious fraction (urban areas shed rain regardless of the VSA) ─────────
# Per-cell impervious fraction Imp ∈ [0,1].  Effective runoff per cell is
#   rain · [ Imp + (1 − Imp) · max(in_VSA, infiltration_excess_fraction) ]
# so urbanised cells contribute even when their upslope area is below A_t.
#   'lcz'    → impervious_fraction column of LCZ_LOOKUP_CSV (reuses cached LCZ raster)
#   'lulc'   → impervious_fraction column of LULC_LOOKUP_CSV (ESA WorldCover)
#   'raster' → pre-computed continuous impervious-fraction GeoTIFF (IMPERVIOUS_RASTER_PATH)
#   'none'   → no impervious contribution (Imp = 0 everywhere)
IMPERVIOUS_SOURCE      = 'lcz'
IMPERVIOUS_RASTER_PATH = None

# ── Baseflow ──────────────────────────────────────────────────────────────────
# OPM_BASEFLOW: seed every cell with the steady pre-storm discharge implied by
#   OPM_Q_MAX so the outlet hydrograph starts at baseflow instead of zero, making
#   simulated hydrographs directly comparable to observed (gauged) discharge.
#   False → hydrograph starts at 0 (original behaviour).
OPM_BASEFLOW = False


# ═════════════════════════════════════════════════════════════════════════════
# 6.  SERVES / GEE SOIL-MOISTURE DEFICIT  (SD_max & phi from satellite)
# ═════════════════════════════════════════════════════════════════════════════

# OPM_SD_SOURCE:
#   'manual' → use OPM_SD_MAX_INITIAL and OPM_PHI above
#   'gee'    → SERVES deficit + LULC/LCZ root zone depth + SoilGrids porosity
OPM_SD_SOURCE  = 'gee'

# OPM_SD_REDUCER: how to turn the per-cell SERVES deficit into one SD_max per
#   precipitation zone.  SD_max is the dominant control on the VSA, so this choice
#   matters a lot:
#     'mean'   → representative (zone-average) deficit; outlier-robust.
#     'max'    → largest deficit in the zone = max soil-STORAGE-capacity cell.
#                NOTE: deficit = (porosity − θ)·Z_r, so with variable root depth
#                Z_r this is biased toward DEEP-ROOTED cells, not necessarily the
#                driest soil — it is NOT a pure "driest cell" proxy.
#     'divide' → deficit sampled AT each zone's divide cell (the topographic
#                headwater where the sandbox water balance actually runs), so the
#                SD_max ceiling is consistent with the sandbox.  Falls back to the
#                zone max-finite deficit, then the watershed SD_max, if the divide
#                cell has no SERVES data (cloud gap).
OPM_SD_REDUCER = 'max'

# Per-cell deficit raster (date-stamped per event by _resolve_sd_params).
OPM_DEFICIT_RASTER = None   # None → auto-path: {OUTPUT_DIR}/deficit_serves_{date}.tif

SERVES_SATELLITE     = 'landsat'   # 'landsat' | 'sentinel2' | 'modis'
SERVES_SEARCH_WINDOW = 30          # days backward from EVENT_START_UTC

# SoilGrids depth band for field capacity / wilting point / porosity.
OPM_SOILGRIDS_DEPTH = 'b30'        # 'b0' 'b10' 'b30' 'b60' 'b100' 'b200'


# ═════════════════════════════════════════════════════════════════════════════
# 7.  MANNING'S ROUGHNESS  (kinematic-wave routing)
# ═════════════════════════════════════════════════════════════════════════════

# MANNINGS_N_SOURCE:
#   'scalar' → uniform MANNINGS_N
#   'lulc'   → ESA WorldCover  → LULC_LOOKUP_CSV (§1)
#   'lcz'    → WUDAPT LCZ      → LCZ_LOOKUP_CSV  (§1); also sets OPM root zone depth
#   'raster' → pre-computed GeoTIFF
MANNINGS_N_SOURCE = 'lcz'

MANNINGS_N = 0.09   # uniform fallback / nodata default

# LULC raster path (source='lulc'):  'gee' → download ESA WorldCover from GEE
MANNINGS_N_LULC_PATH = 'gee'

# Pre-computed Manning's n raster (source='raster')
MANNINGS_N_RASTER_PATH = None

# Channel roughness override for cells above CHANNEL_FACCUM_THRESHOLD.
# Float → uniform channel n.  Dict → per Strahler order.  None → disabled.
MANNINGS_N_CHANNEL = 0.035
'''
MANNINGS_N_CHANNEL = {
    1: 0.10,
    2: 0.06,
    3: 0.045,
    4: 0.035,
}'''

# None → auto (top 1% of watershed cells)
CHANNEL_FACCUM_THRESHOLD = None


# ═════════════════════════════════════════════════════════════════════════════
# 8.  GRID & NUMERICAL LIMITS
# ═════════════════════════════════════════════════════════════════════════════

# None → auto-detected from ROUTING_DEM_PATH at run-time (recommended).
CELL_SIZE = None

# ── Routing scheme ────────────────────────────────────────────────────────────
# ROUTING_SCHEME:
#   'kinematic' → Manning on the static bed slope S₀ (default; current behaviour,
#                 bit-for-bit reproducible).
#   'diffusive' → CASC2D/GSSHA-style diffusion wave: Manning on the *water-surface*
#                 slope  S_w = (z_i−z_ds)/dist + θ·(h_i−h_ds)/dist, with conveyance on the
#                 flow-depth-over-the-higher-bed.  Adds peak attenuation and adverse-
#                 gradient slowdown along the drainage network.  Costs one extra
#                 downstream gather per step (no Δx² penalty).
#   'muskingum' → Muskingum–Cunge (variable-parameter, Ponce–Yevjevich).  A kinematic-
#                 wave scheme whose *numerical* diffusion is tuned (via the weighting
#                 factor X) to equal the *physical* hydraulic diffusivity D=Q/(2·B·S₀),
#                 so peak attenuation is physically correct AND grid-independent — unlike
#                 the storage-cell kinematic/diffusive schemes whose attenuation drifts
#                 with cell size Δx.  Each D8 cell is a reach; K=Δx/c, X=½(1−q/(S₀·c·Δx))
#                 are recomputed per cell per step from the local celerity c=5/3·V.
#                 DIFFUSION_THETA is ignored.
ROUTING_SCHEME = 'muskingum'

# DIFFUSION_THETA: diffusion weight θ∈[0,1] (used only when ROUTING_SCHEME='diffusive').
#   0 → bed-slope-only (≈ kinematic)   |   1 → full water-surface-slope diffusion wave.
DIFFUSION_THETA = 1

# ── Channel (river) cross-section routing ─────────────────────────────────────
# CHANNEL_ROUTING: when True, high-flow-accumulation "channel" cells are routed
#   as a confined RECTANGULAR channel (width B ≪ cell_size, true hydraulic radius
#   R = A/P) instead of a wide sheet spread over the whole DEM cell.  Hillslope
#   (overland) cells are unchanged — they keep the wide-channel R ≈ depth shortcut,
#   which is exact for a thin sheet over a 100 m cell.  Channel cells are the same
#   cells flagged by CHANNEL_FACCUM_THRESHOLD (§7) for the Manning's-n override.
#   False → original behaviour (every cell is a wide sheet of width = cell_size).
CHANNEL_ROUTING = True

# CHANNEL_WIDTH_BY_ORDER: channel width B [m] per Strahler stream order (computed
#   from the D8 network).  Orders above the largest key reuse the largest key's
#   width.  This basin's network spans orders 1–8 and the channel mask
#   (CHANNEL_FACCUM_THRESHOLD, top ~1% of cells) selects roughly orders 4–8, so the
#   table covers up to 8 — otherwise every main-stem cell would cap at the order-4
#   width.  EDIT THESE to your basin (survey/imagery widths of the main
#   Bagmati/Sundarijal channel); the defaults are a generic downstream-widening law.
CHANNEL_WIDTH_BY_ORDER = {1: 3.0, 2: 5.0, 3: 8.0, 4: 12.0,
                          5: 18.0, 6: 28.0, 7: 45.0, 8: 70.0}   # m

# Δt must satisfy the Courant criterion: Δt ≤ CELL_SIZE / V_max
# Used as the initial/fallback dt; ignored per-step when ADAPTIVE_TIMESTEP=True.
TIME_STEP_SECONDS = 2

# How often to record a hydrograph row (seconds of simulation time).
# None → write every time step.
OUTPUT_INTERVAL_SECONDS = 600

# ── Adaptive CFL timestep ─────────────────────────────────────────────────────
# ADAPTIVE_TIMESTEP: when True, dt is re-derived each step from the actual wave
#   celerity c = (5/3)·V on the wet domain; False → static TIME_STEP_SECONDS.
# CFL_TARGET: target Courant number; dt = CFL_TARGET·dx/c_max with the wave
#   celerity c = (5/3)·Q/(h_flow·dx).  Pure advective CFL for BOTH schemes (a
#   von Neumann diffusion-number term was tried and removed — D ∝ S_eff^(-1/2)
#   pinned dt at the floor on flat-water cells; stability comes from the volume
#   flux limiter, not from dt).
#   TRADEOFF (first-order upwind, numerical diffusion D_num = (c·dx/2)(1−C)):
#   higher C (→1) = less numerical diffusion = SHARPER, more physical peak, but
#   more dispersive ripple; lower C = smoother but a damped/smeared peak.  With
#   the interval-averaged hydrograph cleaning sub-step ripple, prefer C HIGH:
#   0.7 is safe, try 0.85 for a sharper peak.  Watch the flux-limiter % — if it
#   climbs you're too near C=1 (limiter engaging adds its own error).
# CFL_DT_MAX: ceiling on dt [s]; None → OUTPUT_INTERVAL_SECONDS.
#   Caps dt during dry/quiescent periods so the rising limb stays resolved.
# CFL_DT_MIN: floor on dt [s]; flux limiter covers cells needing a smaller step.
#   When it binds, a one-line warning + end-of-run count are printed.
# WHY ADAPTIVE: a small static dt (≈0.9 s) over-diffuses (damps/smears the peak)
#   and is slow; adaptive holds Courant near CFL_TARGET → a sharper, less-damped
#   peak and far fewer steps.  The previous adaptive "saw-tooth" was NOT a routing
#   instability — it was the hydrograph being point-sampled (instantaneous outlet
#   rate) once per output step, which aliases sub-step dispersive ripples and the
#   adaptive-dt jitter.  The outlet is now reported as the interval-MEAN flux
#   (ΔV/Δt), which is mass-consistent and invariant to dt jitter → smooth.
ADAPTIVE_TIMESTEP = True
CFL_TARGET        = 0.85
CFL_DT_MAX        = 5   # None → OUTPUT_INTERVAL_SECONDS
CFL_DT_MIN        = 0.01   # [s]
# CFL_DT_GROW: max factor by which adaptive dt may increase in one step.
# Prevents oscillatory blow-up when c_max drops suddenly (GSSHA-style ramp-up).
# 1.5 → dt=0.01s reaches 7s in ~17 steps; set to float('inf') to disable.
CFL_DT_GROW       = 1.5

# Minimum slope (m/m) — floor in Manning's to avoid division-by-zero on flat cells.
MIN_SLOPE   = 1e-4

# Minimum water depth (m) — wet/dry front numerical floor.
MIN_DEPTH_M = 1e-6

# MAX_DEPTH_M: display use only (animation colour scale).
# Depth capping was removed from the router; the flux limiter handles stability.
MAX_DEPTH_M = 10.0


# ═════════════════════════════════════════════════════════════════════════════
# 9.  OUTPUTS
# ═════════════════════════════════════════════════════════════════════════════

HYDROGRAPH_CSV = OUTPUT_DIR + "hydrograph.csv"

# MASS_BALANCE_REPORT: the routing water budget (input − outflow − storage = error) is
# ALWAYS computed and printed for every run/config as a correctness check.  When True,
# also append one row to {OUTPUT_DIR}/mass_balance.csv.
MASS_BALANCE_REPORT = True
MASS_BALANCE_CSV    = OUTPUT_DIR + "mass_balance.csv"


# ═════════════════════════════════════════════════════════════════════════════
# 10. COMPUTE BACKEND
# ═════════════════════════════════════════════════════════════════════════════

# 'cpu' → NumPy  |  'gpu' → CuPy/CUDA (falls back to CPU with warning if unavailable)
BACKEND = 'gpu'

# 'float64' → double precision, matches CPU bit-for-bit
# 'float32' → halves GPU memory; introduces ~1e-7 relative error — validate before use
GPU_PRECISION = 'float64'
